/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import java.io.UnsupportedEncodingException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rmiserver.*;

/**
 *
 * @author DinhTao
 */
public class FrameRegistry extends javax.swing.JFrame {

    ServerInterFace server;
    FrameClient fc;

    /**
     * Creates new form FrameRegistry
     *
     * @param f
     */
    public FrameRegistry(FrameClient f) {
        initComponents();
        fc = f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JUserName = new javax.swing.JTextField();
        jNickName = new javax.swing.JTextField();
        jReset = new javax.swing.JButton();
        jDangKy = new javax.swing.JButton();
        jPasswordRegistry = new javax.swing.JPasswordField();
        jHT = new javax.swing.JTextField();
        jSDT = new javax.swing.JTextField();
        jDiaChi = new javax.swing.JTextField();
        jMonth = new javax.swing.JSpinner();
        jDay = new javax.swing.JSpinner();
        jYear = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đăng ký");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ĐĂNG KÝ");

        jLabel2.setText("Username");

        jLabel3.setText("Password");

        jLabel4.setText("Nickname");

        jReset.setText("Reset");
        jReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetActionPerformed(evt);
            }
        });

        jDangKy.setText("Đăng ký");
        jDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDangKyActionPerformed(evt);
            }
        });

        jMonth.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        jMonth.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jMonthStateChanged(evt);
            }
        });

        jDay.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        jDay.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jDayStateChanged(evt);
            }
        });

        jYear.setModel(new javax.swing.SpinnerNumberModel(1990, 1950, 2010, 1));
        jYear.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jYearStateChanged(evt);
            }
        });

        jLabel5.setText("Ho Tên");

        jLabel6.setText("Ngày Sinh");

        jLabel7.setText("SDT");

        jLabel8.setText("Địa Chỉ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jReset)
                .addGap(18, 18, 18)
                .addComponent(jDangKy)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPasswordRegistry, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jNickName, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jHT, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDay, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(89, 89, 89))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jDangKy, jReset});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JUserName, jDiaChi, jHT, jNickName, jPasswordRegistry, jSDT});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JUserName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordRegistry))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jNickName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jHT)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSDT)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDiaChi)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDangKy)
                    .addComponent(jReset))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetActionPerformed
        JUserName.setText("");
        jPasswordRegistry.setText("");
        jNickName.setText("");
        jHT.setText("");
        jDiaChi.setText("");
        jSDT.setText("");
        jDay.setValue(1);
        jMonth.setValue(1);
        jYear.setValue(1990);
    }//GEN-LAST:event_jResetActionPerformed

    private void jDangKyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDangKyActionPerformed
        try {
            Registry r = LocateRegistry.getRegistry("localhost", 1099);
            server = (ServerInterFace) r.lookup("rmi://localhost/ABC");

            byte[] utf8Bytes = jNickName.getText().getBytes("UTF16");
            String nick = new String(utf8Bytes, "Cp1252");
            utf8Bytes = jHT.getText().getBytes("UTF16");
            String hoten = new String(utf8Bytes, "Cp1252");
            utf8Bytes = jDiaChi.getText().getBytes("UTF16");
            String diachi = new String(utf8Bytes, "Cp1252");

            if (!JUserName.getText().equals("") && !jPasswordRegistry.getText().equals("") && !nick.equals("") && !hoten.equals("") && !jSDT.getText().equals("") && !diachi.equals("")) {
                int y = Integer.parseInt(jYear.getValue().toString());
                int m = Integer.parseInt(jMonth.getValue().toString());
                int d = Integer.parseInt(jDay.getValue().toString());
                ClientInterFace client = new ClientImpl(JUserName.getText(), jPasswordRegistry.getText(), nick, hoten, d + "/" + m + "/" + y, jSDT.getText(), diachi);
                if (server.addAccountServer(client)) {
                    server = null;
                    JOptionPane.showMessageDialog(this, "Tài khoản đã tạo thành công !");
                    fc.jTaiKhoan.setText(JUserName.getText());
                    fc.jPasswordLogin.setText(jPasswordRegistry.getText());
                    fc.jBtnDangKy.setEnabled(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Tài khoản hay NickName đã bị trùng !");
                    JUserName.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin !");
            }
        } catch (RemoteException | NotBoundException ex) {
            JOptionPane.showMessageDialog(this, "Không thể kết nối tới Server !.");
            Logger.getLogger(FrameClient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(FrameRegistry.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jDangKyActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        server = null;
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void jYearStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jYearStateChanged
        setDay();
    }//GEN-LAST:event_jYearStateChanged

    private void jMonthStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jMonthStateChanged
        setDay();
    }//GEN-LAST:event_jMonthStateChanged

    private void jDayStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jDayStateChanged
        setDay();
    }//GEN-LAST:event_jDayStateChanged

    /**
     * @param args the command line arguments
     */
    public void setDay() {
        int y = Integer.parseInt(jYear.getValue().toString());
        int m = Integer.parseInt(jMonth.getValue().toString());
        int d = Integer.parseInt(jDay.getValue().toString());
        switch (m) {
            case 2:
                if (y % 4 == 0 && d > 29) {
                    jDay.setValue(29);
                }
                if (y % 4 != 0 && d > 28) {
                    jDay.setValue(28);
                }
                break;
            case 4:
                if (d > 30) {
                    jDay.setValue(30);
                }
                break;
            case 6:
                if (d > 30) {
                    jDay.setValue(30);
                }
                break;
            case 9:
                if (d > 30) {
                    jDay.setValue(30);
                }
                break;
            case 11:
                if (d > 30) {
                    jDay.setValue(30);
                }
                break;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JUserName;
    private javax.swing.JButton jDangKy;
    private javax.swing.JSpinner jDay;
    private javax.swing.JTextField jDiaChi;
    private javax.swing.JTextField jHT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner jMonth;
    private javax.swing.JTextField jNickName;
    private javax.swing.JPasswordField jPasswordRegistry;
    private javax.swing.JButton jReset;
    private javax.swing.JTextField jSDT;
    private javax.swing.JSpinner jYear;
    // End of variables declaration//GEN-END:variables
}
