/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Client;

import java.rmi.AccessException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rmiserver.*;

/**
 *
 * @author Administrator
 */
public class MainC3online extends javax.swing.JFrame {

    /**
     * Creates new form MainC3online
     */
    public SubServerInterface subServer;

    public FrameClient fc;
    public FrameChatGroup fcg;

    public MainC3online(FrameClient f) throws RemoteException {
        initComponents();
        this.setResizable(false);
        this.setTitle("TK: " + f.client.getUserName() + " - Chát Online 3 Miền");
        fc = f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHaNoi = new javax.swing.JLabel();
        jLabelDaNang = new javax.swing.JLabel();
        jLabelHoChiMinh = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuTaiKhoan = new javax.swing.JMenu();
        jMenuThongTin = new javax.swing.JMenu();
        jMenuDangXuat = new javax.swing.JMenu();
        jMenuThoat = new javax.swing.JMenu();
        jMenuPhanMem = new javax.swing.JMenu();
        jMenuAbout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabelHaNoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hanoi-attractions.jpg"))); // NOI18N
        jLabelHaNoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHaNoiMouseClicked(evt);
            }
        });

        jLabelDaNang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/du-lich-da-nang-ivivu.jpg"))); // NOI18N
        jLabelDaNang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDaNangMouseClicked(evt);
            }
        });

        jLabelHoChiMinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kinh-nghiem-du-lich-sai-gon-trong-1-ngay-2016-3103-1.jpg"))); // NOI18N
        jLabelHoChiMinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHoChiMinhMouseClicked(evt);
            }
        });

        jMenuTaiKhoan.setText("Tài Khoản");

        jMenuThongTin.setText("Tài Khoản");
        jMenuThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuThongTinMouseClicked(evt);
            }
        });
        jMenuTaiKhoan.add(jMenuThongTin);

        jMenuDangXuat.setText("Đăng Xuất");
        jMenuDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuDangXuatMouseClicked(evt);
            }
        });
        jMenuTaiKhoan.add(jMenuDangXuat);

        jMenuThoat.setText("Thoát");
        jMenuThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuThoatMouseClicked(evt);
            }
        });
        jMenuTaiKhoan.add(jMenuThoat);

        jMenuBar.add(jMenuTaiKhoan);

        jMenuPhanMem.setText("Phần Mềm");

        jMenuAbout.setText("About");
        jMenuPhanMem.add(jMenuAbout);

        jMenuBar.add(jMenuPhanMem);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelHaNoi)
            .addComponent(jLabelDaNang)
            .addComponent(jLabelHoChiMinh)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabelHaNoi, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDaNang, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelHoChiMinh, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelHaNoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHaNoiMouseClicked
        try {
            Registry r = LocateRegistry.getRegistry("localhost", 1111);
            subServer = (SubServerInterface) r.lookup("rmi://localhost/HaNoi");
            if (subServer.getStatusSubServer()) {
                if (subServer.addClientSubServer(fc.client)) {
                    fcg = new FrameChatGroup(this);
                    fcg.setVisible(true);
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Thời gian chờ vẫn còn, bạn chưa thể vào phòng chát !.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Số lượng người trong Room đang qua tải !.");
            }
        } catch (RemoteException | NotBoundException ex) {
            JOptionPane.showMessageDialog(this, "Không thể kết nối tới Server Hà Nội !.");
            Logger.getLogger(MainC3online.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelHaNoiMouseClicked

    private void jLabelDaNangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDaNangMouseClicked
        try {
            Registry r = LocateRegistry.getRegistry("localhost", 2222);
            subServer = (SubServerInterface) r.lookup("rmi://localhost/DaNang");
            if (subServer.getStatusSubServer()) {
                if (subServer.addClientSubServer(fc.client)) {
                    fcg = new FrameChatGroup(this);
                    fcg.setVisible(true);
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Thời gian chờ vẫn còn, bạn chưa thể vào phòng chát !.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Số lượng người trong Room đang qua tải !.");
            }
        } catch (RemoteException | NotBoundException ex) {
            JOptionPane.showMessageDialog(this, "Không thể kết nối tới Server Đà Nẵng !.");
            Logger.getLogger(MainC3online.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelDaNangMouseClicked

    private void jLabelHoChiMinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHoChiMinhMouseClicked
        try {
            Registry r = LocateRegistry.getRegistry("localhost", 3333);
            subServer = (SubServerInterface) r.lookup("rmi://localhost/HCM");
            if (subServer.getStatusSubServer()) {
                if (subServer.addClientSubServer(fc.client)) {
                    fcg = new FrameChatGroup(this);
                    fcg.setVisible(true);
                    this.setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Thời gian chờ vẫn còn, bạn chưa thể vào phòng chát !.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Số lượng người trong Room đang qua tải !.");
            }
        } catch (RemoteException | NotBoundException ex) {
            JOptionPane.showMessageDialog(this, "Không thể kết nối tới Server Hồ Chí Minh !.");
            Logger.getLogger(MainC3online.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabelHoChiMinhMouseClicked

    private void jMenuThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuThoatMouseClicked
        try {
            fc.server.disAccountServer(fc.client);
            fc.server = null;
            System.exit(0);
        } catch (RemoteException ex) {
            System.exit(0);
            Logger.getLogger(MainC3online.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuThoatMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            fc.server.disAccountServer(fc.client);
            fc.server = null;
            System.exit(0);
        } catch (RemoteException ex) {
            System.exit(0);
            Logger.getLogger(MainC3online.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jMenuDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuDangXuatMouseClicked
        try {
            fc.server.disAccountServer(fc.client);
            fc.server = null;
            fc.client = null;
        } catch (RemoteException ex) {
            System.exit(0);
            Logger.getLogger(MainC3online.class.getName()).log(Level.SEVERE, null, ex);
        }
        fc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuDangXuatMouseClicked

    private void jMenuThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuThongTinMouseClicked
        try {
            FrameProfile fp = new FrameProfile(this);
            fp.setVisible(true);
            this.setEnabled(false);
        } catch (RemoteException ex) {
            Logger.getLogger(MainC3online.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuThongTinMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDaNang;
    private javax.swing.JLabel jLabelHaNoi;
    private javax.swing.JLabel jLabelHoChiMinh;
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuDangXuat;
    private javax.swing.JMenu jMenuPhanMem;
    private javax.swing.JMenu jMenuTaiKhoan;
    private javax.swing.JMenu jMenuThoat;
    private javax.swing.JMenu jMenuThongTin;
    // End of variables declaration//GEN-END:variables
}
